### PR TITLE
Build macOS app and extend the README.md regarding macOS release

### PR DESCRIPTION
**Pull request by Ecostack**
- The macOS app is now properly packaged as a .app file
- The readme has been extended

One thing to mention here is that unsigned apps can have trouble being executed if downloaded. I described this in the README. Ultimately, if you are interested in having a distribution without these signing issues, an Apple developer account is necessary.

This one contains a couple of more changes, please let me know if you want things changed.

Screenshot 2024-03-13 at 10 39 14

### CODE REVIEW

**Comment by mlange-42** [comment]
Using `.zip` instead of `.tar.gz` is certainly good for accessibility by people not using Linux.

However, I am not really happy with the MacOS instructions being like the longest section of the README 😆.
Maybe we can instead link to some external docs that provide this information?

Also took a brief look at how to sign the app. Look like it requires XCode, which requires MacOS (or another Apple OS). Great...

**Comment by Ecostack** [comment]
Yeah, regarding .zip, I think we can also do the same thing for the Windows build.

I can fully understand that this is a bit out of place maybe. Maybe we have a separate macOS file for that?

As for the signing the app, we could do that during the GitHub action build process. The macOS variant is already using macOS instances instead of the Ubuntu instances. 
It would be up to you if you want to embark on the journey of getting a developer account. IMO, it is not required right now. It might be just awkward if the user does not know about how to open it without signature.

**Comment by mlange-42** [comment]
> I can fully understand that this is a bit out of place maybe. Maybe we have a separate macOS file for that?

Or maybe even move all information on using and building locally to a separate page? It could then also be linked from the itch.io download section.

**Comment by mlange-42** [comment]
I would prefer to move the MacOS / general local usage/"installation" stuff to `INSTALL.md` or so. Also, it would be great if you could change to `.zip` for windows builds.

Besides that, this can be merged.

**Pull request merged**
